In [5]:
i=input()
j=input()
k=input()
if i < j:
    if j < k:
        i = j
    else:
        j = k
else:
    if j > k:
        j = i
    else:
        i = k
print(i, j, k)

In [8]:
hours_worked = 50
level = 1
wage = 100
salary = 0

#salary calculation
if hours_worked > 40:
    salary = 40 * wage + (hours_worked - 40) * wage * 1.5
    level += 1
else:
    salary = hours_worked * wage
print(salary)
        
#bonus calculation
if level >= 5:
    salary += 0.5*salary
    salary += 200
elif level < 5 and level >= 2:
    salary += 0.2*salary
    salary += 10
else:
    salary = salary
print(salary)

#tax deduction
if salary > 5000:
    salary -= salary*0.3
else:
    salary -= salary*0.1

print(salary)

5500.0
6610.0
4627.0

In [28]:
import math
r = float(input("Radius of sphere"))
v = 4/3*math.pi*r*r*r
s = 4*math.pi*r**2
print("Volume is:",v,",","Surface Area is:",s)

ValueError: could not convert string to float: ''

In [39]:
c = float(input("Cost price:"))
if c <= 50000:
    t_rate = 0.025
elif c > 50000 and c <= 100000:
    t_rate = 0.05
else:
    t_rate = 0.15
print(c,c*t_rate)

3832.0 95.80000000000001

In [44]:
year = int(input("Year:"))
if year%100 == 0:
    if year%400 == 0:
        print(year,"is a leap year.")
    else:
        print(year,"is not a leap year.")
else:
    if year%4 == 0:
        print(year,"is a leap year.")
    else:
        print(year,"is not a leap year.")

2006 is not a leap year.

In [49]:
salary = 12190
bonus_rate = .05
bonus = salary * bonus_rate
assert salary
print(salary)
salary = salary+bonus
assert salary
print(salary)
salary = salary+(salary*bonus_rate)
assert salary
print(salary)
if salary> 13000:
    #give extra 200
    salary += 2000
else:
    #give extra 150
    salary += 150
assert salary
print(salary)

12190
12799.5
13439.475
15439.475